import express from 'express';
import cors from 'cors';
import path from 'path';
import { ChatOpenAI } from "@langchain/openai";
import { HumanMessage, AIMessage, BaseMessage } from "@langchain/core/messages";
import { MODEL, OPENAI_API_KEY } from "./config";
import { VectorizationManager } from "./vectorization_manager";
import { buildRetrieverTool } from "./tools";
import { buildGraph } from "./graph";
import { VectorStore } from "@langchain/core/vectorstores";

const app = express();
const PORT = 3000;

app.use(cors());
app.use(express.json());
app.use(express.static(path.join(__dirname, '../public')));

// Global State (Simple In-Memory)
const manager = new VectorizationManager();
let currentPdf: string | null = null;
let currentVectorStore: VectorStore | null = null;
let graph: any = null;

// Helper to initialize graph
function updateGraph() {
    if (!currentVectorStore || !currentPdf) return;

    const retrieverTool = buildRetrieverTool(currentVectorStore, currentPdf);
    const llm = new ChatOpenAI({
        modelName: MODEL,
        openAIApiKey: OPENAI_API_KEY,
        temperature: 0,
        streaming: true // Enable streaming
    });

    graph = buildGraph(llm, [retrieverTool]);
    console.log(`Graph updated for ${currentPdf}`);
}

// Routes

// 1. List PDFs
app.get('/api/pdfs', async (req, res) => {
    try {
        const pdfs = await manager.listAvailablePdfs();
        res.json({ pdfs });
    } catch (error: any) {
        res.status(500).json({ error: error.message });
    }
});

// 2. Vectorize PDF
app.post('/api/vectorize', async (req, res) => {
    try {
        const { filename } = req.body;
        if (!filename) {
            return res.status(400).json({ error: "Filename is required" });
        }

        const result = await manager.vectorizePdf(filename);

        currentPdf = filename.endsWith('.pdf') ? filename : filename + '.pdf';
        currentVectorStore = result.vectorStore;
        updateGraph();

        res.json({ message: result.message, currentPdf });
    } catch (error: any) {
        console.error("Vectorization error:", error);
        res.status(500).json({ error: error.message });
    }
});

// 3. Get Current Status
app.get('/api/status', (req, res) => {
    res.json({
        currentPdf,
        isReady: !!graph
    });
});

// 4. Chat endpoint (SSE)
app.get('/api/chat', async (req, res) => {
    const message = req.query.message as string;

    if (!message) {
        return res.status(400).json({ error: "Message is required" });
    }

    if (!graph) {
        // If no graph (no PDF loaded), we can just send a simple error event or 400
        // But for SSE we usually want to send an event.
        res.writeHead(200, {
            'Content-Type': 'text/event-stream',
            'Cache-Control': 'no-cache',
            'Connection': 'keep-alive',
        });
        res.write(`data: ${JSON.stringify({ type: 'error', content: "Please load a PDF first." })}\n\n`);
        return res.end();
    }

    // Set headers for SSE
    res.writeHead(200, {
        'Content-Type': 'text/event-stream',
        'Cache-Control': 'no-cache',
        'Connection': 'keep-alive',
    });

    try {
        // We use graph.stream() to get events
        // The graph stream returns a sequence of state updates.
        // We want to stream the tokens generated by the LLM if possible, 
        // OR just stream the state updates (like "thinking...", "tool call...", "answer...").
        // LangGraph stream usually yields state updates.

        const stream = await graph.stream({
            messages: [new HumanMessage(message)]
        });

        for await (const chunk of stream) {
            // chunk is a partial state update. 
            // e.g. { llm: { messages: [AIMessage] } }
            // or { tools: { messages: [ToolMessage] } }

            // We want to extract relevant info to send to client.

            // If it's a tool output
            if (chunk.tools) {
                const toolUrl = chunk.tools.messages?.[0]?.content; // Simplification
                res.write(`data: ${JSON.stringify({ type: 'info', content: 'Using tool...' })}\n\n`);
            }

            // If it's LLM output
            if (chunk.llm) { // Depending on node name
                const lastMsg = chunk.llm.messages?.[chunk.llm.messages.length - 1];
                if (lastMsg) {
                    // This is usually the FULL message for that step, not a token stream, 
                    // unless we use specific streaming setup in LangGraph.
                    // For "true" token streaming, we might need graph.streamEvents() if available in this validation
                    // or just send the chunks. 

                    // Sending the full generated message as one chunk for now (simulated stream of steps)
                    res.write(`data: ${JSON.stringify({ type: 'answer', content: lastMsg.content })}\n\n`);
                }
            }
        }

        res.write(`data: [DONE]\n\n`);
        res.end();

    } catch (error: any) {
        console.error("Chat error:", error);
        res.write(`data: ${JSON.stringify({ type: 'error', content: error.message })}\n\n`);
        res.end();
    }
});

app.listen(PORT, () => {
    console.log(`Server running on http://localhost:${PORT}`);
});
