import express from 'express';
import cors from 'cors';
import path from 'path';
import { ChatOpenAI } from "@langchain/openai";
import { HumanMessage, AIMessage, BaseMessage, ToolMessage } from "@langchain/core/messages";
import { MODEL, OPENAI_API_KEY } from "./config";
import { VectorizationManager } from "./vectorization_manager";
import { buildRetrieverTool } from "./tools";
import { buildGraph } from "./graph";
import { calculatorTool } from "./calculator_tool";
import { webSearchTool } from "./web_search_tool";
import { VectorStore } from "@langchain/core/vectorstores";

const app = express();
const PORT = 3000;

app.use(cors());
app.use(express.json());
app.use(express.static(path.join(__dirname, '../public')));

// Global State (Simple In-Memory)
const manager = new VectorizationManager();
let currentPdf: string | null = null;
let currentVectorStore: VectorStore | null = null;
let graph: any = null;

// Helper to initialize graph
function updateGraph() {
    if (!currentVectorStore || !currentPdf) return;

    const retrieverTool = buildRetrieverTool(currentVectorStore, currentPdf);
    const llm = new ChatOpenAI({
        modelName: MODEL,
        openAIApiKey: OPENAI_API_KEY,
        temperature: 0,
        streaming: true // Enable streaming
    });

    graph = buildGraph(llm, [retrieverTool, calculatorTool, webSearchTool]);
    console.log(`Graph updated for ${currentPdf} with extra tools (Calculator, Web Search)`);
}

// Routes

// 1. List PDFs
app.get('/api/pdfs', async (req, res) => {
    try {
        const pdfs = await manager.listAvailablePdfs();
        res.json({ pdfs });
    } catch (error: any) {
        res.status(500).json({ error: error.message });
    }
});

// 2. Vectorize PDF
app.post('/api/vectorize', async (req, res) => {
    try {
        const { filename } = req.body;
        if (!filename) {
            return res.status(400).json({ error: "Filename is required" });
        }

        const result = await manager.vectorizePdf(filename);

        currentPdf = filename.endsWith('.pdf') ? filename : filename + '.pdf';
        currentVectorStore = result.vectorStore;
        updateGraph();

        res.json({ message: result.message, currentPdf });
    } catch (error: any) {
        console.error("Vectorization error:", error);
        res.status(500).json({ error: error.message });
    }
});

// 3. Get Current Status
app.get('/api/status', (req, res) => {
    res.json({
        currentPdf,
        isReady: !!graph
    });
});

// 4. Chat endpoint (SSE)
app.get('/api/chat', async (req, res) => {
    const message = req.query.message as string;

    if (!message) {
        return res.status(400).json({ error: "Message is required" });
    }

    if (!graph) {
        // If no graph (no PDF loaded), we can just send a simple error event or 400
        // But for SSE we usually want to send an event.
        res.writeHead(200, {
            'Content-Type': 'text/event-stream',
            'Cache-Control': 'no-cache',
            'Connection': 'keep-alive',
        });
        res.write(`data: ${JSON.stringify({ type: 'error', content: "Please load a PDF first." })}\n\n`);
        return res.end();
    }

    // Set headers for SSE
    res.writeHead(200, {
        'Content-Type': 'text/event-stream',
        'Cache-Control': 'no-cache',
        'Connection': 'keep-alive',
    });

    try {
        // We use graph.stream() to get events
        // The graph stream returns a sequence of state updates.
        // We want to stream the tokens generated by the LLM if possible, 
        // OR just stream the state updates (like "thinking...", "tool call...", "answer...").
        // LangGraph stream usually yields state updates.

        const stream = await graph.stream({
            messages: [new HumanMessage(message)]
        });

        for await (const chunk of stream) {
            // chunk is a partial state update. 
            // e.g. { llm: { messages: [AIMessage] } }
            // or { tools: { messages: [ToolMessage] } }

            // We want to extract relevant info to send to client.

            // If it's a tool output
            if (chunk.tools) {
                const messages = chunk.tools.messages || [];
                for (const msg of messages) {
                    if (msg instanceof ToolMessage || (msg.type === 'tool')) {
                        res.write(`data: ${JSON.stringify({ type: 'info', content: `Tool used: ${msg.name}` })}\n\n`);
                        console.log(`[SSE: Info] Tool used: ${msg.name}`);
                    }
                }
            }

            // If it's LLM output
            if (chunk.llm) {
                const lastMsg = chunk.llm.messages?.[chunk.llm.messages.length - 1];
                if (lastMsg) {
                    // Check if lastMsg has tool calls
                    if (lastMsg.tool_calls && lastMsg.tool_calls.length > 0) {
                        for (const tc of lastMsg.tool_calls) {
                            res.write(`data: ${JSON.stringify({ type: 'info', content: `Thinking... Using tool: ${tc.name}` })}\n\n`);
                        }
                    } else if (lastMsg.content) {
                        // Regular answer
                        res.write(`data: ${JSON.stringify({ type: 'answer', content: lastMsg.content })}\n\n`);
                    }
                }
            }
        }

        res.write(`data: [DONE]\n\n`);
        res.end();

    } catch (error: any) {
        console.error("Chat error:", error);
        res.write(`data: ${JSON.stringify({ type: 'error', content: error.message })}\n\n`);
        res.end();
    }
});

app.listen(PORT, () => {
    console.log(`Server running on http://localhost:${PORT}`);
});
